/**
 * GENERATED by scripts/sales-import-workbook.py from Samer's workbook
 * "Monza-Bot-Reply-Worksheet-Master-Logic-Expanded.xlsx" (A Car Facts, B Showroom).
 * Do not edit by hand: change the workbook and run the script again.
 *
 * Every value here was approved by Samer in that workbook (2026-09-17). A fact with
 * confirmed: false is one the workbook says is not stated: the bot says so, never guesses.
 */

export const WORKBOOK = {
  "models": {
    "FREE_318": {
      "officialName": "VOYAH Free 318",
      "catalogueId": "voyah-free-comp",
      "bucket": "EREV",
      "seatCount": 5,
      "facts": {
        "HORSEPOWER": {
          "value": "600 hp",
          "confirmed": true
        },
        "RANGE": {
          "value": "318 km EV / 1,357 km combined (CLTC)",
          "confirmed": true
        },
        "BATTERY": {
          "value": "",
          "confirmed": false,
          "pending": "43 kWh ternary lithium"
        },
        "POWERTRAIN": {
          "value": "EREV – electric drive with 1.5T petrol range extender",
          "confirmed": true
        },
        "CHARGING": {
          "value": "External charging supported (the exact charging time is not confirmed yet)",
          "confirmed": true
        },
        "SEATS": {
          "value": "5",
          "confirmed": true
        },
        "DIMENSIONS": {
          "value": "4,905 × 1,950 × 1,645 mm · 560 L / 1,320 L folded",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "voyah free 318",
        "free 318",
        "free318",
        "318",
        "voyah free",
        "free",
        "free 318 competition",
        "competition",
        "voyah competition",
        "free competition",
        "voya free 318",
        "voyah 318",
        "فري 318",
        "فري",
        "فوياه فري",
        "فوياه 318"
      ],
      "workbookColours": "Black · Green · Grey · Sage · White"
    },
    "COURAGE": {
      "officialName": "VOYAH Courage",
      "catalogueId": "voyah-courage",
      "bucket": "EV",
      "seatCount": 5,
      "facts": {
        "HORSEPOWER": {
          "value": "320 kW / 435 PS",
          "confirmed": true
        },
        "RANGE": {
          "value": "",
          "confirmed": false,
          "pending": "440 km WLTP"
        },
        "BATTERY": {
          "value": "80 kWh nominal / 77.3 kWh usable LFP",
          "confirmed": true
        },
        "POWERTRAIN": {
          "value": "BEV / Fully Electric",
          "confirmed": true
        },
        "CHARGING": {
          "value": "AC + DC charging supported (the exact charging time is not confirmed yet)",
          "confirmed": true
        },
        "SEATS": {
          "value": "5",
          "confirmed": true
        },
        "DIMENSIONS": {
          "value": "4,725 × 1,900 × 1,650 mm · 527 L / 1,400 L folded",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "voyah courage",
        "courage",
        "courage ev",
        "courage electric",
        "electric courage",
        "courage awd",
        "voyah courage awd",
        "voya courage",
        "كوراج",
        "فوياه كوراج",
        "كوريج"
      ],
      "workbookColours": "Black · Grey · White"
    },
    "DREAM": {
      "officialName": "VOYAH Dream",
      "catalogueId": "voyah-dream",
      "bucket": "PHEV",
      "seatCount": 7,
      "facts": {
        "HORSEPOWER": {
          "value": "416 hp / 310 kW",
          "confirmed": true
        },
        "RANGE": {
          "value": "185 km EV / 915 km combined (WLTC)",
          "confirmed": true
        },
        "BATTERY": {
          "value": "",
          "confirmed": false,
          "pending": "43 kWh ternary lithium"
        },
        "POWERTRAIN": {
          "value": "PHEV – Plug-in Hybrid",
          "confirmed": true
        },
        "CHARGING": {
          "value": "DC 20–80%: ~30 min (80 kW) · AC 0–100%: 8.4 h (6.6 kW)",
          "confirmed": true
        },
        "SEATS": {
          "value": "7 (2+2+3)",
          "confirmed": true
        },
        "DIMENSIONS": {
          "value": "5,315 × 1,985 × 1,820 mm · 427 L",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "voyah dream",
        "dream",
        "voyah dream mpv",
        "dream mpv",
        "dream 7 seater",
        "voyah 7 seater",
        "7 seat voyah",
        "voya dream",
        "دريم",
        "فوياه دريم",
        "فويا دريم"
      ],
      "workbookColours": "black"
    },
    "PASSION": {
      "officialName": "VOYAH Passion",
      "catalogueId": "voyah-passion",
      "bucket": "PHEV",
      "seatCount": 5,
      "facts": {
        "HORSEPOWER": {
          "value": "523 hp / 390 kW",
          "confirmed": true
        },
        "RANGE": {
          "value": "262 km EV / 1,260 km combined (CLTC)",
          "confirmed": true
        },
        "BATTERY": {
          "value": "",
          "confirmed": false,
          "pending": "43 kWh ternary lithium"
        },
        "POWERTRAIN": {
          "value": "PHEV – Plug-in Hybrid",
          "confirmed": true
        },
        "CHARGING": {
          "value": "DC 20–80%: 29 min · AC 0–100%: 8 h",
          "confirmed": true
        },
        "SEATS": {
          "value": "5",
          "confirmed": true
        },
        "DIMENSIONS": {
          "value": "5,088 × 1,970 × 1,505 mm · 410 L",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "voyah passion",
        "passion",
        "passion phev",
        "passion hybrid",
        "passion sedan",
        "voya passion",
        "باشن",
        "باسيون",
        "فوياه باشن"
      ],
      "workbookColours": "black"
    },
    "PASSION_L": {
      "officialName": "VOYAH Passion L",
      "catalogueId": "voyah-passion-l",
      "bucket": "PHEV",
      "seatCount": 5,
      "facts": {
        "HORSEPOWER": {
          "value": "",
          "confirmed": false,
          "pending": "657 hp"
        },
        "RANGE": {
          "value": "",
          "confirmed": false,
          "pending": "410 km EV / 1,400 km combined (CLTC)"
        },
        "BATTERY": {
          "value": "",
          "confirmed": false
        },
        "POWERTRAIN": {
          "value": "Smart Hybrid PHEV · 800V",
          "confirmed": true
        },
        "CHARGING": {
          "value": "800V rapid DC charging (the exact charging time is not confirmed yet)",
          "confirmed": true
        },
        "SEATS": {
          "value": "5",
          "confirmed": true
        },
        "DIMENSIONS": {
          "value": "5,125 × 1,985 × 1,522 mm (trunk capacity not confirmed yet)",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "voyah passion l",
        "passion l",
        "passionl",
        "passion l",
        "passion l hybrid",
        "passion l phev",
        "passion l smart hybrid",
        "voyah passion l",
        "voya passion l",
        "باشن ال",
        "باسيون ال",
        "فوياه باشن ال"
      ],
      "workbookColours": "Black · Grey"
    },
    "TAISHAN": {
      "officialName": "VOYAH Taishan",
      "catalogueId": "voyah-taishan",
      "bucket": "PHEV",
      "seatCount": 6,
      "facts": {
        "HORSEPOWER": {
          "value": "",
          "confirmed": false,
          "pending": "657 hp"
        },
        "RANGE": {
          "value": "",
          "confirmed": false,
          "pending": "370 km EV / 1,400 km combined (CLTC)"
        },
        "BATTERY": {
          "value": "65 kWh CATL ternary lithium",
          "confirmed": true
        },
        "POWERTRAIN": {
          "value": "Smart Super Hybrid – PHEV · 800V",
          "confirmed": true
        },
        "CHARGING": {
          "value": "800V rapid DC charging (the exact charging time is not confirmed yet)",
          "confirmed": true
        },
        "SEATS": {
          "value": "6",
          "confirmed": true
        },
        "DIMENSIONS": {
          "value": "5,230 × 2,025 × 1,817 mm (trunk capacity not confirmed yet)",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "voyah taishan",
        "taishan",
        "tai shan",
        "voyah tai shan",
        "taishan suv",
        "taishan hybrid",
        "taishan 6 seater",
        "6 seat voyah",
        "voyah flagship suv",
        "voya taishan",
        "تايشان",
        "تاي شان",
        "فوياه تايشان"
      ],
      "workbookColours": "Black · Blue · Grey"
    },
    "MHERO_1": {
      "officialName": "MHERO 1",
      "catalogueId": "mhero-1",
      "bucket": "EREV",
      "seatCount": null,
      "facts": {
        "HORSEPOWER": {
          "value": "805 hp",
          "confirmed": true
        },
        "RANGE": {
          "value": "200 km EV / 1,000 km combined (CLTC)",
          "confirmed": true
        },
        "BATTERY": {
          "value": "65.8 kWh",
          "confirmed": true
        },
        "POWERTRAIN": {
          "value": "EREV · triple-motor",
          "confirmed": true
        },
        "CHARGING": {
          "value": "DC 30–80%: ~37 min",
          "confirmed": true
        },
        "SEATS": {
          "value": "",
          "confirmed": false
        },
        "DIMENSIONS": {
          "value": "4,987 × 2,080 × 1,935 mm (trunk capacity not confirmed yet)",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "mhero 1",
        "mhero1",
        "m-hero 1",
        "m hero 1",
        "mhero one",
        "mhero 917",
        "m-hero 917",
        "m hero 917",
        "917",
        "mh917",
        "mhero1 917",
        "mhero 1 917",
        "mengshi 917",
        "منغشي 917",
        "ام هيرو 1",
        "ام هيرو 917",
        "مهيرو 1",
        "مهيرو 917"
      ],
      "workbookColours": "Black · Green ·Grey"
    },
    "MHERO_2": {
      "officialName": "MHERO 2",
      "catalogueId": "mhero-2",
      "bucket": "PHEV",
      "seatCount": 5,
      "facts": {
        "HORSEPOWER": {
          "value": "700 hp / 522 kW",
          "confirmed": true
        },
        "RANGE": {
          "value": "140 km EV / 1,300 km combined (CLTC)",
          "confirmed": true
        },
        "BATTERY": {
          "value": "31.7 kWh LFP",
          "confirmed": true
        },
        "POWERTRAIN": {
          "value": "PHEV · dual-motor",
          "confirmed": true
        },
        "CHARGING": {
          "value": "DC 20–80%: ~15 min",
          "confirmed": true
        },
        "SEATS": {
          "value": "5",
          "confirmed": true
        },
        "DIMENSIONS": {
          "value": "5,100 × 1,998 × 1,899 mm (trunk capacity not confirmed yet)",
          "confirmed": true
        },
        "WARRANTY": {
          "value": "6 years on the vehicle and 10 years on the battery",
          "confirmed": true
        }
      },
      "aliases": [
        "mhero 2",
        "mhero2",
        "m-hero 2",
        "m hero 2",
        "mhero two",
        "mhero 817",
        "m-hero 817",
        "m hero 817",
        "817",
        "mh817",
        "mhero2 817",
        "mhero 2 817",
        "mengshi 817",
        "منغشي 817",
        "ام هيرو 2",
        "ام هيرو 817",
        "مهيرو 2",
        "مهيرو 817"
      ],
      "workbookColours": "Black · Green · White"
    }
  },
  "showroom": {
    "location": "Our showroom is located in Horch Tabet, Beirut.",
    "hoursWeek": "Our showroom is open Monday to Friday, from 8:00 AM to 6:00 PM.",
    "hoursSaturday": "Our showroom is open on Saturday, from 8:00 AM to 2:00 PM.",
    "hoursSunday": "Sunday and public-holiday availability should be confirmed by a team member.",
    "salesContact": "For sales enquiries, please contact us on 70 70 85 85.",
    "serviceContact": "For Service, Maintenance, or Spare Parts, please contact 76 877 278.",
    "welcome": "Hello and welcome to Monza S.A.L. How can we help you today?",
    "handoff": "For further assistance, please contact us on 70 70 85 85.",
    "mapsLink": "https://maps.app.goo.gl/orJMduowHtVqQgR58",
    "administration": "01 488 333 / 01 488 666"
  }
} as const;
